app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

use App\Task;
use Illuminate\Http\Request;

Route::get('/', function () {
    return view('welcome');
});


Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Registration Routes...
Route::get('register', 'Auth\AuthController@getRegister');
Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::get('/home', 'HomeController@index');

Route::resource('books', 'BookController');

app/Models/Book.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="Book",
 *      required={},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="title",
 *          description="title",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="author",
 *          description="author",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="year",
 *          description="year",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="units",
 *          description="units",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="price",
 *          description="price",
 *          type="number",
 *          format="float"
 *      )
 * )
 */
class Book extends Model
{
    use SoftDeletes;

    public $table = 'books';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];

    protected $primaryKey = 'id';

    public $fillable = [
        'title',
        'author',
        'year',
        'units',
        'price',
        'timeMark'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'author' => 'string',
        'year' => 'integer',
        'units' => 'integer',
        'price' => 'float',
        'timeMark' => 'datetime'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Requests\CreateBookRequest;
use App\Http\Requests\UpdateBookRequest;
use App\Repositories\BookRepository;
use App\Http\Controllers\AppBaseController as InfyOmBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class BookController extends InfyOmBaseController
{
    /** @var  bookRepository */
    private $bookRepository;

    public function __construct(bookRepository $bookRepo)
    {
        $this->bookRepository = $bookRepo;
    }

    /**
     * Display a listing of the books.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->bookRepository->pushCriteria(new RequestCriteria($request));
        $books = $this->bookRepository->all();

        return view('book.index')
            ->with('books', $books);
    }

    /**
     * Show the form for creating a new books.
     *
     * @return Response
     */
    public function create()
    {
        return view('book.create');
    }

    /**
     * Store a newly created book in storage.
     *
     * @param CreateBookRequest $request
     *
     * @return Response
     */
    public function store(CreateBookRequest $request)
    {
        $input = $request->all();

        $book = $this->bookRepository->create($input);

        Flash::success('Book saved successfully.');

        return redirect(route('book.index'));
    }

    /**
     * Display the specified book.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $book = $this->bookRepository->findWithoutFail($id);

        if (empty($book)) {
            Flash::error('book not found');

            return redirect(route('book.index'));
        }

        return view('book.show')->with('book', $book);
    }

    /**
     * Show the form for editing the specified books.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $book = $this->bookRepository->findWithoutFail($id);

        if (empty($book)) {
            Flash::error('book not found');

            return redirect(route('book.index'));
        }

        return view('book.edit')->with('book', $books);
    }

    /**
     * Update the specified book in storage.
     *
     * @param  int              $id
     * @param UpdateBookRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateBookRequest $request)
    {
        $book = $this->bookRepository->findWithoutFail($id);

        if (empty($books)) {
            Flash::error('book not found');

            return redirect(route('book.index'));
        }

        $book = $this->bookRepository->update($request->all(), $id);

        Flash::success('book updated successfully.');

        return redirect(route('book.index'));
    }

    /**
     * Remove the specified book from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $book = $this->bookRepository->findWithoutFail($id);

        if (empty($book)) {
            Flash::error('book not found');

            return redirect(route('books.index'));
        }

        $this->bookRepository->delete($id);

        Flash::success('book deleted successfully.');

        return redirect(route('books.index'));
    }
}

resources/views/book/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h1 class="pull-left">Create New Book</h1>
        </div>
    </div>

    @include('core-templates::common.errors')

    <div class="row">
        {!! Form::open(['route' => 'books.store']) !!}

            @include('book.fields')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/book/edit.blade.php
@extends('layouts.app')

@section('content')
        <div class="row">
            <div class="col-sm-12">
                <h1 class="pull-left">Edit Book</h1>
            </div>
        </div>

        @include('core-templates::common.errors')

        <div class="row">
            {!! Form::model($book, ['route' => ['book.update', $book->id], 'method' => 'patch']) !!}

            @include('book.fields')

            {!! Form::close() !!}
        </div>
@endsection

resources/views/book/fields.blade.php
<!-- Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Id', 'Id:') !!}
    {!! Form::number('Id', null, ['class' => 'form-control']) !!}
</div>

<!-- Title Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Title', 'Title:') !!}
    {!! Form::text('Title', null, ['class' => 'form-control']) !!}
</div>

<!-- Author Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Author', 'Author:') !!}
    {!! Form::text('Author', null, ['class' => 'form-control']) !!}
</div>

<!-- Year Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Year', 'Year:') !!}
    {!! Form::number('Year', null, ['class' => 'form-control']) !!}
</div>

<!-- Units Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Units', 'Units:') !!}
    {!! Form::number('Units', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Price', 'Price:') !!}
    {!! Form::number('Price', null, ['class' => 'form-control']) !!}
</div>

<!-- Timemark Field -->
<div class="form-group col-sm-6">
    {!! Form::label('TimeMark', 'Timemark:') !!}
    {!! Form::date('TimeMark', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('books.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/book/index.blade.php
@extends('layouts.app')

@section('content')
        <h1 class="pull-left">books</h1>
        <a class="btn btn-primary pull-right" style="margin-top: 25px" href="{!! route('books.create') !!}">Add New</a>

        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        @include('book.table')
        
@endsection

resources/views/book/show.blade.php
@extends('layouts.app')

@section('content')
    @include('book.show_fields')

    <div class="form-group">
           <a href="{!! route('books.index') !!}" class="btn btn-default">Back</a>
    </div>
@endsection

resources/views/book/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('Id', 'Id:') !!}
    <p>{!! $book->id !!}</p>
</div>

<!-- Title Field -->
<div class="form-group">
    {!! Form::label('Title', 'Título:') !!}
    <p>{!! $book->title !!}</p>
</div>

<!-- Author Field -->
<div class="form-group">
    {!! Form::label('Author', 'Autor:') !!}
    <p>{!! $book->author !!}</p>
</div>

<!-- Year Field -->
<div class="form-group">
    {!! Form::label('Year', 'Año:') !!}
    <p>{!! $book->year !!}</p>
</div>

<!-- Units Field -->
<div class="form-group">
    {!! Form::label('Units', 'Unidades:') !!}
    <p>{!! $book->units !!}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('Price', 'Precio:') !!}
    <p>{!! $book->price !!}</p>
</div>

<!-- Timemark Field -->
<div class="form-group">
    {!! Form::label('timeMark', 'Marca temporal:') !!}
    <p>{!! $book->timeMark !!}</p>
</div>

resources/views/book/table.blade.php
<table class="table table-responsive" id="books-table">
    <thead>
        <th>Título</th>
        <th>Autor</th>
        <th>Año</th>
        <th>Unidades</th>
        <th>Precio</th>
        <th>Marca temporal</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($books as $book)
        <tr>
            <td>{!! $book->title !!}</td>
            <td>{!! $book->author !!}</td>
            <td>{!! $book->year !!}</td>
            <td>{!! $book->units !!}</td>
            <td>{!! $book->price !!}</td>
            <td>{!! $book->timeMark !!}</td>
            <td>
                {!! Form::open(['route' => ['books.destroy', $book->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('books.show', [$book->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('books.edit', [$book->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>